#!/usr/bin/env groovy

node {
    stage('checkout') {
        checkout scm
    }

    stage('check java') {
        sh "java -version"
    }

    stage('clean') {
        sh "cd ./store && chmod +x mvnw"
        sh "cd ./store && ./mvnw -ntp clean -P-webpack"
    }
    stage('nohttp') {
        sh "cd ./store && ./mvnw -ntp checkstyle:check"
    }

    stage('backend tests') {
        try {
            sh "cd ./store && ./mvnw -ntp verify -P-webpack"
        } catch(err) {
            throw err
        } finally {
            junit '**/target/test-results/**/TEST-*.xml'
        }
    }

    stage('packaging') {
        sh "cd ./store && ./mvnw -ntp verify -P-webpack -Pprod -DskipTests"
        archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
    }
    stage('quality analysis') {
        withSonarQubeEnv('sonar') {
            sh "cd ./store && ./mvnw -ntp initialize sonar:sonar"
        }
    }
}
