#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MDYwMTUwM2VmN2Q2ZDhkMjdlMDliOTEzMDZhYzZkYTZiMmRjMWQ2Mzg2ZmVhYWU3YjNhNzcwM2NlNjQ1ZTY3YjA5ZDM1Zjg5MDA1ZTdmMGM4ZGQ4MjJiOTllZTExYTgyNjY1ZA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
