version: '3'
services:
  sonar:
    image: 'sonarqube:8.3.1-community'
    ports:
      - '9001:9000'
      - '9092:9092'
  jenkins:
    image: jenkins/jenkins
    ports:
      - '18080:8080'
      - '50000:50000'